local: 
  URL_LIST: ['https://www.amazon.com/dp/B00125Q75Y']
  BOOTSTRAP_SERVERS: ['localhost:9092']
  VALUE_SERIALIZER: 'lambda m: json.dumps(m).encode("utf-8")'
  VALUE_DESERIALIZER: 'lambda m: json.loads(m.decode("utf-8")'
  SQL_ENGINE: 'mysql+pymysql://root:root@localhost:3306/amzorbit?charset=utf8'
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION_NAME: 'us-east-1'
  SCHEDULER_INTERVEL: 3600
  APP_HOST: '0.0.0.0'
  APP_PORT: 8082
  MAILGUN_API_KEY:
  MAILGUN_DOMAIN_NAME:
  APP_IP: 'http://localhost:3000'

dev:
  URL_LIST: ['https://www.amazon.com/dp/B00125Q75Y']
  BOOTSTRAP_SERVERS: ['localhost:9092']
  VALUE_SERIALIZER: 'lambda m: json.dumps(m).encode("utf-8")'
  VALUE_DESERIALIZER: 'lambda m: json.loads(m.decode("utf-8")'
  SQL_ENGINE: 
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION_NAME: 'us-east-1'
  SCHEDULER_INTERVEL: 3600
  APP_HOST: '0.0.0.0'
  APP_PORT: 8082
  MAILGUN_API_KEY:
  MAILGUN_DOMAIN_NAME:
  APP_IP: 'http://107.23.120.9:8083'

prod:
  URL_LIST: ['https://www.amazon.com/dp/B00125Q75Y']
  BOOTSTRAP_SERVERS: ['localhost:9092']
  VALUE_SERIALIZER: 'lambda m: json.dumps(m).encode("utf-8")'
  VALUE_DESERIALIZER: 'lambda m: json.loads(m.decode("utf-8")'
  SQL_ENGINE:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY: 
  AWS_REGION_NAME: 'us-east-1'
  SCHEDULER_INTERVEL: 3600
  APP_HOST: '0.0.0.0'
  APP_PORT: 8082
  MAILGUN_API_KEY:
  MAILGUN_DOMAIN_NAME:
  APP_IP: 'https://app.amzorbit.com'

